library(shiny)
library(esd)

# Choices for drop-downs
# Show a tabset that includes a plot, summary, and
# table view of the generated distribution

Z4 <- list()
load('data/dse.aaca.t2m.rcp45.djf.eof.rda')
Z4$djf.45 <- Z
locs <<- loc(Z4[[1]]$pca)
gcmnames <<- names(Z4[[1]])[-c(1,2,length(Z4[[1]]))]

navbarPage("AACA Barents region climate atlas",
    tabPanel("Maps", 
             column(2,
                    selectInput("param1", 
                                label = "Element",
                                choices = c("Temperature"),
                                selected = "Temperature")),
             column(2, 
                    selectInput("season1", 
                                label = "Season",
                                choices = c("Winter", "Spring","Summer","Autumn"),
                                selected = "Winter")),
             column(3,
                    sliderInput("lon1", 
                                label = "Longitudes",
                                min = 0, max = 50, value = c(0, 50))),
             column(3,
                    sliderInput("lat1", 
                                label = "Latitudes",
                                min = 65, max = 85, value = c(65, 85))),
             column(3,
                    sliderInput("dates1", "Years", 
                                min=1900, max=2099, value= c(2050,2050),sep="")),
             column(2, 
                    selectInput("rcp1", 
                                label = "Scenario", 
                                choices = c("RCP4.5","RCP2.6", "RCP8.5"),
                                selected = "RCP4.5")),
             plotOutput("maps")
             ),
    tabPanel("Single location", 
             column(2,
                    selectInput("location2", 
                                label = "Location",
                                choices = locs,
                                selected = "longyearbyen")),
             column(2,
                    selectInput("param2", 
                                label = "Element",
                                choices = c("Temperature"),
                                selected = "Temperature")),
             column(2, 
                    selectInput("season2", 
                                label = "Season",
                                choices = c("Winter", "Spring","Summer","Autumn"),
                                selected = "Winter")),
             column(2, 
                    selectInput("rcp2", 
                                label = "Scenario", 
                                choices = c("RCP4.5","RCP2.6", "RCP8.5"),
                                selected = "RCP4.5")),
             plotOutput("plot")),
        tabPanel("Multiple locations", 
#             column(3,
#                    checkboxGroupInput("locations", 
#                                      label = "Locations",
#                                       choices = locs,
#                                       selected = locs)),
            column(3,
                    sliderInput("lon3", 
                             label = "Longitudes",
                             min = 0, max = 50, value = c(0, 50))),
            column(3,
                   sliderInput("lat3", 
                             label = "Latitudes",
                             min = 65, max = 85, value = c(65, 85))),
             column(3,
                   sliderInput("alt3", 
                             label = "Elevation",
                             min = 0, max = 2000, value = c(0, 2000))),
             column(3,
                     sliderInput("dates3", "Years", 
                                min=1900, max=2099, value= c(1900,2099),sep="")),
             column(2,
                    selectInput("param3", 
                                label = "Element",
                                choices = c("Temperature"),
                                selected = "Temperature")),
             column(2, 
                    selectInput("season3", 
                               label = "Season",
                                choices = c("Winter", "Spring","Summer","Autumn"),
                                selected = "Winter")),
             column(2, 
                    selectInput("rcp3", 
                                label = "Scenario", 
                                choices = c("RCP4.5","RCP2.6", "RCP8.5"),
                                selected = "RCP4.5")),
             plotOutput("plot.multi")),
    tabPanel("Probabilities", 
             column(2,
                    selectInput("location4", 
                                label = "Location",
                                choices = locs,
                                selected = locs[1])),
             column(2,
                    selectInput("param4", 
                                label = "Element",
                                choices = c("Temperature"),
                                selected = "Temperature")),
             column(2, 
                    selectInput("season4", 
                                label = "Season",
                                choices = c("Winter", "Spring","Summer","Autumn"),
                                selected = "Winter")),
             column(2, 
                    selectInput("rcp4", 
                                label = "Scenario", 
                                choices = c("RCP4.5","RCP2.6", "RCP8.5"),
                                selected = "RCP4.5")),
             column(3,
                    sliderInput("dates4", "Years", 
                                min=1900, max=2099, value= c(2045,2055),sep="")),
             column(2, 
                    selectInput("direction4", 
                                label = "Direction",
                                choices = c("Colder", "Warmer"),
                                selected = "Colder")),
             column(2, 
                    numericInput("threshold4", "Threshold", 0.0, min = -50.0, max = 50.0)),
             plotOutput("plot.prob")),
tabPanel("Warm/cold days",  ## Unfinished!
         column(2,
                selectInput("location5", 
                            label = "Location",
                            choices = locs,
                            selected = locs[1])),
         column(2,
                selectInput("param5", 
                            label = "Element",
                            choices = c("Temperature"),
                            selected = "Temperature")),
         column(2, 
                selectInput("season5", 
                            label = "Season",
                            choices = c("Winter", "Spring","Summer","Autumn"),
                            selected = "Winter")),
         
         plotOutput("plot.warmcolddays")),
    tabPanel("Quality",  ## Unfinished!
             column(2,
                    selectInput("param6", 
                                label = "Element",
                                choices = c("Temperature"),
                                selected = "Temperature")),
             column(2, 
                    selectInput("season6", 
                                label = "Season",
                                choices = c("Winter", "Spring","Summer","Autumn"),
                                selected = "Winter")),
             column(2, 
                    selectInput("rcp6", 
                                label = "Scenario", 
                                choices = c("RCP4.5","RCP2.6", "RCP8.5"),
                                selected = "RCP4.5")),
             column(3,
                    sliderInput("lon6", 
                                label = "Longitudes",
                                min = 0, max = 50, value = c(0, 50))),
             column(3,
                    sliderInput("lat6", 
                                label = "Latitudes",
                                min = 65, max = 85, value = c(65, 85))),
            plotOutput("map.quality")
    ),
    tabPanel("Settings", ## Unfinished! Aslo include settings for maps: text
             column(2,
                    selectInput("aspect", 
                                label = "Aspect",
                                choices = c("Mean value", "Change","Trend","Scenario difference"),
                                selected = "Mean value")
             ),
             column(3,
                    selectInput("stats", 
                                label = "Statistic",
                                choices = c("Ensemble mean", "95-percentile","5-percentile","Individual model",
                                            "Ensemble spread","Model difference","Pr(X>x)","Pr(X<x)"),
                                selected = "Ensemble mean")
             ),
             column(2, 
                    checkboxGroupInput("im", 
                                       label = "Model run", 
                                       choices = gcmnames,
                                       selected=gcmnames)),
             
             
             tableOutput("table")),
    tabPanel("Usage statistics",  ## Unfinished!
             column(2,
                    checkboxGroupInput("user.stats", 
                                       label = "Statistics",
                                       choices = c('views','season','aspect'),
                                       selected = 1)
             ),
             plotOutput("plot.ens")),
    tabPanel("Disclaimer & info", 
         column(2,
                checkboxGroupInput("user.stats", 
                                   label = "Statistics",
                                   choices = c('views','season','aspect'),
                                   selected = 1)
         ))
)
